name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - api/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  

    defaults:
      run:
        working-directory: api
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest   
      
      - name: Install dependencies
        run: bun install

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKER }}
          workingDirectory: api
